### ISSUE TITLE
The bookmarking icon next to the repository name is gone

### ISSUE THREAD

**Issue by xmhwws** [ovity/octotree#1127]
### Description
If this is a bug, provide as much information as you can to help reproduce the issue.
The bookmarking icon next to the repository name is gone

* Octotree version:7.4.3
* Browser & version:Chrome 102.0.4997.0 dev 
* OS & version:win11
* Screenshot, if any (drag an image here)
<img width="394" alt="2022-04-19_12-42-48" src="https://user-images.githubusercontent.com/42903751/163921739-ef635b64-164f-45dc-8df3-710a2a58b00e.png">

**Comment by xmhwws** [comment]
@danhgit Please fix the bugs as soon as possible

**Comment by danhgit** [comment]
This was fixed in 7.5.0. Sorry for taking long.

**Comment by xmhwws** [comment]
@danhgit 7.5.0, The bug is back and the issue is going to reopen.
