### ISSUE TITLE
Body pushed too far right with new code view

### ISSUE THREAD

**Issue by jdreesen** [ovity/octotree#1150]
### Description
When the feature preview of the [new code view](https://docs.github.com/en/repositories/working-with-files/managing-files/navigating-files-with-the-new-code-view) (which is [currently in beta](https://github.com/orgs/community/discussions/38692)) is enabled, the body is pushed too far right on those pages.

### Environment (if bug)

* Octotree version: v7.7.1
* Browser & version: Firefox 109.0.1 (64-Bit)
* OS & version: Windows 10 Pro 22H2 / Ubuntu 20.04.5 LTS

https://user-images.githubusercontent.com/424602/216623134-16324fa5-ee35-4175-bc89-a018fe51ec94.mp4

**Comment by danhgit** [comment]
@jdreesen thanks for reporting the bug and providing detailed info. We've fixed the bug and released with version 7.8.

**Comment by jdreesen** [comment]
The update is finally approved. It seems to work now, thx for the quick fix! :)

**Comment by jdreesen** [comment]
It doesn't always seem to work everywhere yet. I cannot yet say exactly where and when, but the problem persists in some places 😞

**Comment by danhgit** [comment]
@jdreesen thanks for noticing. Does it happen on the file page or pull request and other pages? Anything to help reproduce would be very helpful. Thanks.

**Comment by jdreesen** [comment]
I'll tell you when it happens again.

**Comment by jdreesen** [comment]
I just found an example where is wrong again: https://github.com/pimcore/pimcore/blob/10.5/bundles/InstallBundle/Installer.php

![grafik](https://user-images.githubusercontent.com/424602/222287727-ccbc516b-1b4e-4d61-b3f3-f2f7db9d6aa8.png)

**Comment by jdreesen** [comment]
Here are other examples: 

- https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/Serializer/Context/ContextBuilderTrait.php
![grafik](https://user-images.githubusercontent.com/424602/222958339-10817a3e-333a-4003-a3b9-f489fc997027.png)
- https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/index.rst#getting-started
![grafik](https://user-images.githubusercontent.com/424602/222959207-9ab9c16f-9304-4532-bc20-dcff60e362e9.png)

It just seems to happen when I browse the code.

**Comment by danhgit** [comment]
Thanks @jdreesen. We've just pushed v7.8.2 to the stores, hopefully will appear soon. Please check after a couple of days and let us know if this problem is fixed.

**Comment by jdreesen** [comment]
It seems like it's still not available on AMO. Latest version there is `7.8.0` 😞

**Comment by danhgit** [comment]
Sorry about that, the release is still pending Mozilla review. We'll see if we could ask them to speed up.

**Comment by danhgit** [comment]
It's available now. Please give it a try and let me know if the bug is resolved. Thanks for your patience.
