### ISSUE TITLE
Octotree font change options makes text copying very difficult

### ISSUE THREAD

**Issue by ahatzz11** [ovity/octotree#1155]
### Description
When changing the font settings (either font itself or the text size) in octotree, it can make copying code very difficult because it seems to 'change' the code that is actually present on the screen. It seems like octotree changes the color of the underlying font, and then puts new font on top of it. 

Here is an example where I'm trying to copy `- name: Create Summary - Fail` but it actually ends up copying some text "under" that text and it doesn't align with what my screen shows.
<img width="407" alt="image" src="https://user-images.githubusercontent.com/6256032/235965855-c41b59fb-19ee-45d5-ba79-ea5d34287e44.png">

This example is from using JetBrains Mono with size 13px. Every change to font seems to do this with varying levels of issue. Happy to give more information if needed!

### Environment (if bug)

* Octotree version: 7.9.0
* Browser & version: Chrome 112.0.5615.137
* OS & version: Mac OS 13.3.1
* Screenshot, if any (drag an image here): See Above
* Console error log below this line

**Comment by jibbers42** [comment]
Same issue. The ghosted text is present when changing the font, but changing the size is what really makes the selectable content drift from the visible content.

- Octotree 7.9.0
- Firefox 113.0.1
- OS
  - Windows 11 Pro
  - Version 22H2
  - OS build 22621.1702
  - Experience Windows Feature Experience Pack 1000.22641.1000.0

**Comment by danhgit** [comment]
@ahatzz11 thanks for reporting with details.

@mgray88 I understand your concern, rest assured Octotree is not abandoned and we've been updating it regularly. This bug is a bit tough so I haven't reported back, but we should have the fix soon. Will keep everyone updated.

**Comment by mgray88** [comment]
Thank you @danhgit!
I want to extend my sincere appreciation for this project. I know GitHub have themselves been implementing some of the functionality natively, but I still find I prefer Octotree. The font/text size is big deal to me, so thank you for reporting back!

**Comment by ahatzz11** [comment]
I am super thrilled to hear there is still some work going on for this. The octotree code tree is still far superior to GitHub's in my opinion, Thanks @danhgit!

**Comment by mgray88** [comment]
Significantly improved! There's still a strange behavior with the visual location of the cursor. Not critical though :grin: 

Using JetBrains Mono; 14px

*   Octotree 7.9.1
*   Arc Browser; Chromium Engine Version 113.0.5672.126
*   MacOS 13.2

I clicked on `indexOf` and the symbol highlighting works, and I can select text correctly, but that visual cursor that GitHub shows seems to still be aligned with the smaller font size

![](https://github.com/ovity/octotree/assets/411747/0b2cfd55-7705-41d7-a4fe-de27b9e66ba3)

**Comment by danhgit** [comment]
@mgray88 missed that... We've just release the fix in 7.9.2. Please look out for that version.

**Comment by BenjaVR** [comment]
> @mgray88 missed that... We've just release the fix in 7.9.2. Please look out for that version.

I still have the cursor thing using v7.9.2.

**Comment by danhgit** [comment]
Can you add screenshot?

**Comment by BenjaVR** [comment]
> 

Sure:
![image](https://github.com/ovity/octotree/assets/17981138/3dde68ed-244e-45c0-9855-163db77fb79d)

Note it is blinking now. I think before it was just static.

**Comment by ahatzz11** [comment]
> @mgray88 @ahatzz11: thank you so much for your support and kind words! I'm happy to let you know that we've released a fix for the bug in version 7.9.1, which is now available on Chrome and will soon be available on other platforms.

Thank you for the fix! Super super glad to see that improvements are still being made, even for little QoL things. Thanks!

**Comment by danhgit** [comment]
@BenjaVR we fixed the issue in v7.9.3. Please check out and let me know if it works for you. I'm closing the ticket now.

**Comment by BenjaVR** [comment]
> @BenjaVR we fixed the issue in v7.9.3. Please check out and let me know if it works for you. I'm closing the ticket now.

I'm on this version:
![image](https://github.com/ovity/octotree/assets/17981138/66ca3fec-13a1-49dc-b2d7-e1f21104656e)

But I still see the blinking cursor while looking at code:
![image](https://github.com/ovity/octotree/assets/17981138/44313dae-9032-484c-ab37-704f1c08426a)

**Comment by BenjaVR** [comment]
> The blinking cursor is a GitHub thing I believe. You can disable Octotree and it will still blink.

Hmm, when I open a random file on GitHub in an incognito window without any extensions, I do not see the cursor. However, when logged in I do 😁 GitHub feature it is! Thanks 🙂
